spring:
  data:
  mongodb:
    uri:
    database: visium
    auto-index-creation: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: example@gmail.com
    password: xxxxx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080
  servlet:
    context-path: /uptime